### ISSUE TITLE
companion on and off works, but toggle action doesn't toggle tuya via homeassistant-server

### ISSUE THREAD

**Issue by lvnilesh** [bitfocus/companion-module-homeassistant-server#14]
Toggle used to work, but I upgraded bitfocus/companion to version     2.2.0 (2.2.0-71b95b9d-3683)

I observe the following:

- homeassistant toggles tuya lights successfully
- companion can turn ON tuya lights via homeassistant
- companion can turn OFF tuya lights via homeassistant
- companion can NOT toggle tuya lights via homeassistant

What am I missing?

**Comment by Julusian** [comment]
Does the correct on/off state show in home-assistant?
Does the feedback in companion for the on/off state of the entity work?

**Comment by lvnilesh** [comment]
When activated via companion, the Light turns ON but homeassistant shows OFF. Strange.
Feedback in companion does NOT reflect the ON state. Also strange.
I have just one light entity.
It consistently turns OFF and always turns OFF via Companion but Homeassistant shows OFF all the time.
Feedback in companion does not reflect the light state.

Where should I look next?

**Comment by Julusian** [comment]
This sounds like something weird going on in homeassistant, as it is showing that the light is off even when it is on.
companion relies on the data from homeassistant to know the state of things, so it matching what is shown in homeassistant makes sense.

The toggling works by us looking at what homeassistant last told us the device is (is it on or off) and issuing a turn_on or turn_off to perform the toggle, so with it always showing as off we will always be issues an on as that is what we believe the toggle should be.

So I think you need to look into getting homeassistant to know the correct on/off state for the light

**Comment by lvnilesh** [comment]
Exactly. 

The homeassistant app provided via [getumbrel](https://getumbrel.com/) is busted. 

I ran my own docker instance using homeassistant latest and all is well.

**Comment by lvnilesh** [comment]
Thanks for your help @Julusian
