### ISSUE TITLE
High CPU Load with a lot of entities in home assistant

### ISSUE THREAD

**Issue by minideezel** [bitfocus/companion-module-homeassistant-server#42]
I have a largish home assistant setup for my whole house. (250 devices, 2500 entities) and while the home assistant integration does work, the cpu load is very high (100% of a core) with this running. When I toggle off the home assistant connection cpu load drops down to basically nothing for the companion process. 

My guess is it's because it's updating 2 variables per entity on some periodic basis. Unless there's something else that's also causing it. Is there anyway to get it to only update the entities that are actually being utilized?

**Comment by Julusian** [comment]
I've pushed an update to the module which reduced the cpu impact on my dev machine from 0.5% to 0.1%, and my home setup from 16% to 2.5%

Hopefully it gives similar results for you

**Comment by AJolly** [comment]
> I've pushed an update to the module which reduced the cpu impact on my dev machine from 0.5% to 0.1%, and my home setup from 16% to 2.5%
> 
> Hopefully it gives similar results for you

Which build is this?

**Comment by Julusian** [comment]
> > I've pushed an update to the module which reduced the cpu impact on my dev machine from 0.5% to 0.1%, and my home setup from 16% to 2.5%
> > 
> > Hopefully it gives similar results for you
> 
> Which build is this?

It is in the 3.4 releases by now

**Comment by AJolly** [comment]
> > > I've pushed an update to the module which reduced the cpu impact on my dev machine from 0.5% to 0.1%, and my home setup from 16% to 2.5%
> > > Hopefully it gives similar results for you
> > 
> > 
> > Which build is this?
> 
> It is in the 3.4 releases by now

Got it. Unfortunately I was considering downgrading from 3.4 - It seems to keep running the same powershell commands on my system over and over.  
![image](https://github.com/user-attachments/assets/f5ef1d5f-1fb4-4f14-bf69-5b4e70aca5a1)

**Comment by Julusian** [comment]
I think that powershell issue is the same as https://github.com/bitfocus/companion/issues/3113, not related to this module
